export interface GoogleFont {
    family: string;
    category: string;
}

export const TOP_GOOGLE_FONTS: GoogleFont[] = [
    { family: "Roboto", category: "sans-serif" },
    { family: "Open Sans", category: "sans-serif" },
    { family: "Noto Sans JP", category: "sans-serif" },
    { family: "Lato", category: "sans-serif" },
    { family: "Montserrat", category: "sans-serif" },
    { family: "Inter", category: "sans-serif" },
    { family: "Roboto Condensed", category: "sans-serif" },
    { family: "Oswald", category: "sans-serif" },
    { family: "Source Sans 3", category: "sans-serif" },
    { family: "Poppins", category: "sans-serif" },
    { family: "Roboto Mono", category: "monospace" },
    { family: "Playfair Display", category: "serif" },
    { family: "Ubuntu", category: "sans-serif" },
    { family: "Merriweather", category: "serif" },
    { family: "Noto Sans", category: "sans-serif" },
    { family: "Lora", category: "serif" },
    { family: "PT Sans", category: "sans-serif" },
    { family: "Nunito", category: "sans-serif" },
    { family: "Dosis", category: "sans-serif" },
    { family: "Mukta", category: "sans-serif" },
    { family: "Raleway", category: "sans-serif" },
    { family: "Bebas Neue", category: "display" },
    { family: "Arvo", category: "serif" },
    { family: "Libre Baskerville", category: "serif" },
    { family: "Rubik", category: "sans-serif" },
    { family: "Work Sans", category: "sans-serif" },
    { family: "Quicksand", category: "sans-serif" },
    { family: "Kanit", category: "sans-serif" },
    { family: "Amiri", category: "serif" },
    { family: "Fira Sans", category: "sans-serif" },
    { family: "Nanum Gothic", category: "sans-serif" },
    { family: "Titillium Web", category: "sans-serif" },
    { family: "PT Serif", category: "serif" },
    { family: "Barlow", category: "sans-serif" },
    { family: "Heebo", category: "sans-serif" },
    { family: "Pacifico", category: "handwriting" },
    { family: "IBM Plex Sans", category: "sans-serif" },
    { family: "Inconsolata", category: "monospace" },
    { family: "Dancing Script", category: "handwriting" },
    { family: "Caveat", category: "handwriting" },
    { family: "Yellowtail", category: "handwriting" },
    { family: "Anton", category: "sans-serif" },
    { family: "Abril Fatface", category: "display" },
    { family: "Josefin Sans", category: "sans-serif" },
    { family: "Teko", category: "sans-serif" },
    { family: "Varela Round", category: "sans-serif" },
    { family: "Righteous", category: "display" },
    { family: "Comfortaa", category: "display" },
    { family: "Lobster", category: "display" },
    { family: "Shadows Into Light", category: "handwriting" },
    { family: "Cormorant Garamond", category: "serif" },
    { family: "Domine", category: "serif" },
    { family: "Bitter", category: "serif" },
    { family: "Crimson Text", category: "serif" },
    { family: "Cinzel", category: "serif" },
    { family: "Alfa Slab One", category: "display" },
    { family: "Zilla Slab", category: "serif" },
    { family: "Spectral", category: "serif" },
    { family: "Vollkorn", category: "serif" },
    { family: "Old Standard TT", category: "serif" },
    { family: "Questrial", category: "sans-serif" },
    { family: "Exo 2", category: "sans-serif" },
    { family: "Karla", category: "sans-serif" },
    { family: "Prompt", category: "sans-serif" },
    { family: "Abel", category: "sans-serif" },
    { family: "Asap", category: "sans-serif" },
    { family: "Catamaran", category: "sans-serif" },
    { family: "Hind", category: "sans-serif" },
    { family: "Oxygen", category: "sans-serif" },
    { family: "Maven Pro", category: "sans-serif" },
    { family: "Muli", category: "sans-serif" },
    { family: "Jost", category: "sans-serif" },
    { family: "Manrope", category: "sans-serif" },
    { family: "Syne", category: "sans-serif" },
    { family: "Space Grotesk", category: "sans-serif" },
    { family: "Sen", category: "sans-serif" },
    { family: "Be Vietnam Pro", category: "sans-serif" },
    { family: "Lexend", category: "sans-serif" },
    { family: "Urbanist", category: "sans-serif" },
    { family: "Fraunces", category: "serif" },
    { family: "Eczar", category: "serif" },
    { family: "Martel", category: "serif" },
    { family: "Space Mono", category: "monospace" },
    { family: "JetBrains Mono", category: "monospace" },
    { family: "VT323", category: "monospace" },
    { family: "Creepster", category: "display" },
    { family: "Monoton", category: "display" },
    { family: "Permanent Marker", category: "handwriting" },
    { family: "Satisfy", category: "handwriting" },
    { family: "Great Vibes", category: "handwriting" },
    { family: "Courgette", category: "handwriting" },
    { family: "Gloria Hallelujah", category: "handwriting" },
    { family: "Indie Flower", category: "handwriting" },
    { family: "Handlee", category: "handwriting" },
    { family: "Homemade Apple", category: "handwriting" },
    { family: "Rock Salt", category: "handwriting" },
    { family: "Kaushan Script", category: "handwriting" },
    { family: "Bangers", category: "display" },
    { family: "Luckiest Guy", category: "display" },
    { family: "Press Start 2P", category: "display" }
];

export const getGoogleFontUrl = (fontFamily: string, textPreview: string | null = null) => {
    const encodedFamily = encodeURIComponent(fontFamily);
    const weights = "wght@400;700";
    let url = `https://fonts.googleapis.com/css2?family=${encodedFamily}:${weights}`;
    if (textPreview) {
        url += `&text=${encodeURIComponent(textPreview)}`;
    }
    url += `&display=swap`;
    return url;
};
